version: "3.9"
services:
  mongodb:
    container_name: alkitab-mongodb
    image: mongo:5.0.9-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: books
    # TODO: Change to expose for production
    ports:
      - 27017:27017
    networks:
      - alkitab

  alkitab-backend:
    container_name: alkitab-backend
    build:
      context: ./backend
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_DB_NAME: books
      MONGO_PORT: 27017
      USERNAME: root
      PASS: 123456
    networks:
      - alkitab
    # TODO: Change to expose for production
    ports:
      - 3000:3000

  alkitab-frontend:
    container_name: alkitab-frontend
    build:
      context: ./frontend
      args:
        VITE_ALKITAB_BACKEND_PORT: 8080
        VITE_ALKITAB_BACKEND_URL: localhost
    depends_on:
      - alkitab-backend
    networks:
      - alkitab
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # Testing for developing
  cors-proxy:
    container_name: alkitab-cors-proxy
    image: nginx:1.23-alpine
    depends_on:
      - alkitab-backend
    networks:
      - alkitab
    volumes:
      - ./nginx/cors-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8010:80
    profiles:
      - develop

networks:
  alkitab:
