version: "3.9"
services:
  mongodb:
    container_name: alkitab-mongodb
    image: mongo:5.0.9-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: books
    ports:
      - 27017:27017
    networks:
      - alkitab
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  alkitab-backend:
    container_name: alkitab-backend
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_DB_NAME: books
      MONGO_PORT: 27017
      USERNAME: root
      PASS: 123456
      PORT: 3000
    networks:
      - alkitab
    expose:
      - 3000

  alkitab-frontend:
    container_name: alkitab-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        VITE_ALKITAB_BACKEND_PORT: 8080
        VITE_ALKITAB_BACKEND_URL: localhost
    depends_on:
      - alkitab-backend
    networks:
      - alkitab
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  alkitab-mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: alkitab-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: alkitab-mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 123456
      # ME_CONFIG_SITE_BASEURL: /mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - alkitab

  alkitab-portainer:
    image: portainer/portainer-ce:2.14.1-alpine
    container_name: alkitab-portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    environment:
      VIRTUAL_HOST: /portainer
      VIRTUAL_PORT: 9000
    networks:
      - alkitab
    expose:
      - 9000

  alkitab-cors-proxy:
    container_name: alkitab-cors-proxy
    image: nginx:1.23-alpine
    depends_on:
      - alkitab-backend
    volumes:
      - ./nginx/cors-proxy.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host"
    profiles:
      - develop

networks:
  alkitab:

volumes:
  portainer-data:
  mongo-data:
  mongo-config: