version: "3.9"
services:
  mongodb:
    container_name: alkitab-mongodb
    image: mongo:5.0.9-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: books
    # TODO: Change to expose for production
    ports:
      - 27017:27017
    networks:
      - alkitab

  alkitab-backend:
    container_name: alkitab-backend
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_DB_NAME: books
      MONGO_PORT: 27017
      USERNAME: root
      PASS: 123456
      PORT: 3000
    networks:
      - alkitab
    # TODO: Change to expose for production
    ports:
      - 3000:3000

  alkitab-frontend:
    container_name: alkitab-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        VITE_ALKITAB_BACKEND_PORT: 3000
        VITE_ALKITAB_BACKEND_URL: localhost
    depends_on:
      - alkitab-backend
    networks:
      - alkitab
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  alkitab-mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: alkitab-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: alkitab-mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 123456
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - alkitab
    profiles:
      - develop

networks:
  alkitab:
