apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alkitab-certificate
  # namespace: cert-manager
spec:
  dnsNames:
    - www.cscc09-alkitab.ninja
    # - cscc09-alkitab.ninja
  secretName: alkitab-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
